id: P000601
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:50:18.272953
source_metadata:
  id: bdr:W1KG14511
  title: དཀར་བཟློག་དམར་བཟློག
  author: ''
  volumes:
    580a9516a2b1442989293efe2ccb0fc4:
      image_group_id: I1KG15656
      title: ''
      volume_number: 1
      total_pages: 452
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
