id: P000601
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14511
  title: དཀར་བཟློག་དམར་བཟློག
  author: ''
  volumes:
    580a9516a2b1442989293efe2ccb0fc4:
      image_group_id: I1KG15656
      title: ''
      volume_number: 1
      total_pages: 452
