id: I85716D8B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T21:43:34+00:00'
last_modified: '2022-06-07T12:25:34.493040+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14511
  title: དཀར་བཟློག་དམར་བཟློག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    0D0C:
      image_group_id: I1KG15656
      title: ''
      total_pages: 452
      order: 1
      base_file: 0D0C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
